// client/src/components/DebouncedInput.tsx
import { useEffect, useState } from 'react';

export function DebouncedInput<T extends string | number>({
    value: initialValue,
    onChange,
    debounce = 500,
    ...props
}: {
    value?: T;
    onChange: (value: T) => void;
    debounce?: number;
} & Omit<React.InputHTMLAttributes<HTMLInputElement>, 'onChange' | 'value'>) {
    const [value, setValue] = useState<any>(initialValue);

    useEffect(() => {
        setValue(initialValue);
    }, [initialValue]);

    useEffect(() => {
        const timeout = setTimeout(() => {
            onChange(value);
        }, debounce);

        return () => clearTimeout(timeout);
    }, [value]);

    return (
        <input
            {...props}
            value={value}
            onChange={(e) => setValue(e.target.value)}
        />
    );
}

// solidjs/client/src/components/DebouncedInput.tsx
import { createEffect, createSignal, JSX } from 'solid-js';
import { debounce } from '@solid-primitives/scheduled';

export function DebouncedInput({
    value: initialValue,
    onChange,
    wait = 500,
    ...props
}: {
    value?: string;
    onChange: (value: string) => void;
    wait?: number;
} & Omit<
    JSX.InputHTMLAttributes<HTMLInputElement>,
    'onChange' | 'value' | 'onInput'
>) {
    const [value, setValue] = createSignal(initialValue || '');
    const debouncedInput = debounce((value: string) => onChange(value), wait);

    createEffect(() => {
        debouncedInput(value());
    });

    return (
        <input
            {...props}
            value={value()}
            onInput={(e) => setValue(() => e.currentTarget.value)}
        />
    );
}
