// client/src/pages/pokemon-list/pokemon.tsx
import { createSignal } from 'solid-js';
import { CgSearchLoading as LoadingIcon } from 'solid-icons/cg';
import { Link } from '@solidjs/router';

export const Pokemon = ({
    name,
    image,
    id,
}: {
    name: string;
    image: string;
    id: number;
}) => {
    const [isLoaded, setIsLoaded] = createSignal(false);

    return (
        <Link
            href={`/${id}`}
            class="w-1/5 flex flex-col items-center min-w-[150px]"
        >
            {!isLoaded && <LoadingIcon class="w-full h-fit animate-pulse" />}
            <img
                src={image}
                alt={name}
                class={`w-full ${
                    isLoaded() ? '' : 'invisible h-0'
                } hover:animate-bounce`}
                onLoad={() => setIsLoaded(true)}
            />
            <div class="flex flex-row capitalize font-semibold -mt-5 text-lg gap-2">
                <div>{name}</div>
            </div>
        </Link>
    );
};

// client/src/pages/pokemon-page/pokemon.tsx
import { useParams } from 'react-router-dom';
import { trpc } from 'utils/trpc';

export const PokemonPage = () => {
    let { id } = useParams();

    const { data, isLoading, isError } = trpc.useQuery([
        'pokemon.get',
        {
            id: Number(id),
        },
    ]);

    if (isLoading) {
        return <>loding</>;
    }

    if (isError || !data) {
        return <>error</>;
    }

    return (
        <div className="h-full w-full flex items-center justify-center p-40">
            <div className="w-1/3">
                <img
                    src={data.image}
                    alt={data.name}
                    className="w-full h-fit"
                />
            </div>
            <div className="flex-1 rounded-lg border-2 border-solid border-poke-yellow h-full px-10 py-5 flex flex-col gap-2">
                <div className="text-4xl capitalize font-bold">{data.name}</div>
                <div>
                    <ul>
                        <li>Height: {data.height}cm</li>
                        <li>Weight: {data.weight}kg</li>
                        <li>species: {data.species.name}</li>
                        <li>
                            Abilities:
                            <ul>
                                {data.abilities.map((ability) => (
                                    <li className="pl-8 capitalize">
                                        {ability.name}
                                    </li>
                                ))}
                            </ul>
                        </li>
                        <li>
                            Types:
                            <ul>
                                {data.types.map((type) => (
                                    <li className="pl-8 capitalize">
                                        {type.name}
                                    </li>
                                ))}
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    );
};
